<option value="">Select Barangay</option>
<option value="Alipit">Alipit</option>
<option value="Malaking Ambling">Malaking Ambling</option>
<option value="Munting Ambling">Munting Ambling</option>
<option value="Baanan">Baanan</option>
<option value="Balanac">Balanac</option>
<option value="Bucal">Bucal</option>
<option value="Buenavista">Buenavista</option>
<option value="Bungkol">Bungkol</option>
<option value="Buo">Buo</option>
<option value="Burlungan">Burlungan</option>
<option value="Cigaras">Cigaras</option>
<option value="Ibabang Atingay">Ibabang Atingay</option>
<option value="Ibabang Butnong">Ibabang Butnong</option>
<option value="Ilayang Atingay">Ilayang Atingay</option>
<option value="Ilayang Butnong">Ilayang Butnong</option>
<option value="Ilog">Ilog</option>
<option value="Malinao">Malinao</option>
<option value="Maravilla">Maravilla</option>
<option value="Poblacion">Poblacion</option>
<option value="Sabang">Sabang</option>
<option value="Salasad">Salasad</option>
<option value="Tanawan">Tanawan</option>
<option value="Tipunan">Tipunan</option>
<option value="Halayhayin">Halayhayin</option>
