<option value="">Select Barangay</option>
<option value="Bakia">Bakia</option>
<option value="Balayang">Balayang</option>
<option value="Banga">Banga</option>
<option value="Banilad">Banilad</option>
<option value="Banti">Banti</option>
<option value="Bukal">Bukal</option>
<option value="Buo">Buo</option>
<option value="Gagalot">Gagalot</option>
<option value="Ilayang Banga">Ilayang Banga</option>
<option value="Ilayang Bayucain">Ilayang Bayucain</option>
<option value="Ilayang Bukal">Ilayang Bukal</option>
<option value="Ilayang Nangka">Ilayang Nangka</option>
<option value="Ilayang Sungi">Ilayang Sungi</option>
<option value="Malinao">Malinao</option>
<option value="Magsaysay">Magsaysay</option>
<option value="May It">May It</option>
<option value="Olla">Olla</option>
<option value="Pangil">Pangil</option>
<option value="Piit">Piit</option>
<option value="Poblacion I">Poblacion I</option>
<option value="Poblacion II">Poblacion II</option>
<option value="Poblacion III">Poblacion III</option>
<option value="Poblacion IV">Poblacion IV</option>
<option value="Pook">Pook</option>
<option value="Quinale">Quinale</option>
<option value="San Francisco">San Francisco</option>
<option value="San Isidro">San Isidro</option>
<option value="San Miguel">San Miguel</option>
<option value="San Roque">San Roque</option>
<option value="Santo Angel">Santo Angel</option>
<option value="Santo Tomas">Santo Tomas</option>
<option value="Sumucab">Sumucab</option>
<option value="Taluntalunan">Taluntalunan</option>
<option value="Taytay">Taytay</option>
<option value="Tingting">Tingting</option>
<option value="Tunhac">Tunhac</option>
<option value="Tubang">Tubang</option>
<option value="Tuong">Tuong</option>
<option value="Yabyaban">Yabyaban</option>
<option value="Yamot">Yamot</option>